config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :restaurants
  resources :categories

  resources :search, only: :create

  authenticated :admin do
    root 'admin_dashboards#index', as: :authenticated_admin
  end

  root 'pages#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :groups
  has_many :restaurants, through: :groups

  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :restaurant
  belongs_to :category
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  # after_create_commit { broadcast_prepend_to "restaurants" }
  after_create_commit :geocode_and_broadcast_changes
  after_update_commit { broadcast_replace_to "restaurants" }
  after_destroy_commit { broadcast_remove_to "restaurants" }

  has_many :groups
  has_many :categories, through: :groups

  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: [:name],
                  using: {
                    tsearch: {
                      prefix: true,
                      highlight: {
                        StartSel: '<b>',
                        StopSel: '</b>'
                      }
                    }
                  }

  private

  def geocode_and_broadcast_changes
    results = Geocoder.search(self.address)

    unless results.nil?
      self.update!(latitude: results.first.coordinates[0], longitude: results.first.coordinates[1])

      broadcast_prepend_to "restaurants"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController
  def index
    @restaurants = Restaurant.all.size
    @categories = Category.all.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: :show
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.includes(:restaurants).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.includes(:restaurants).friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_admin!, except: :show
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @categories = Category.all
    @assigned_categories = @restaurant.categories
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@restaurant, partial: "restaurants/form", locals: { restaurant: @restaurant}) }
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to root_url, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.includes(:categories).friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :latitude, :longitude, :about)
    end
end

app/helpers/admin_dashboards_helper.rb
module AdminDashboardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin_dashboards/_navbar.html.erb
<section class="animated-container"></section>

<nav class="navbar navbar-expand-lg navbar-light shadow-sm" style="background-color: #fff;">
  <a href="/" class="navbar-brand">search<strong>ME</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Platform Management
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <h6 class="dropdown-header">Internal</h6>
          <a class="dropdown-item" href="/categories">Categories</a>
          <a class="dropdown-item" href="/restaurants">Restaurants</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">External</h6>
          <a class="dropdown-item" href="/users">Users</a>
        </div>
      </li>
    </ul>
    
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_admin.email %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to('Sign Out', destroy_admin_session_path, method: :delete, class: 'dropdown-item') %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/admin_dashboards/index.html.erb
<%= render 'navbar' %>

<div class="container mt-5">
  <div class="row">
    <p id="notice"><%= notice %></p>
    <div class="col-md-6">
      <div class="card bs-box" style="padding-top: 20px;">
        <div class="card-body text-center">
          <h2><%= @restaurants %></h2>
          <p>Total restaurants</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card bs-box" style="padding-top: 20px;">
        <div class="card-body text-center">
          <h2><%= @categories %></h2>
          <p>Total categories</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br />
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'admin_dashboards/navbar' %>

<div class="jumbotron text-center">
  <h1>Update Category</h1>
  <%= link_to 'Back', categories_path, class: "btn btn-link" %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form', category: @category %>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/categories/index.html.erb
<%= render 'admin_dashboards/navbar' %>

  <div class="jumbotron text-center">
    <h1>Categories</h1>
  </div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <%= link_to 'New Category', new_category_path, class: "btn btn-success mb-3" %>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %> (<%= category.restaurants.size %>)</td>
              <td><%= link_to 'Show', category %></td>
              <td><%= link_to 'Edit', edit_category_path(category) %></td>
              <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/categories/new.html.erb
<%= render 'admin_dashboards/navbar' %>

<div class="jumbotron text-center">
  <h1>New Category</h1>
  <%= link_to 'Back', categories_path, class: "btn btn-link" %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form', category: @category %>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/categories/show.html.erb
<% if admin_signed_in? %>
  <%= render 'admin_dashboards/navbar' %>
    
  <div class="jumbotron text-center">
    <h1><%= @category.name %></h1>
    <%= link_to 'Update', edit_category_path(@category) %> | <%= link_to 'Back', categories_path, class: "btn btn-link" %>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Assigned restaurants
          </div>

          <div class="card-body">
            <div id="all-restaurants">
              <%= render(Restaurants::ListingComponent.with_collection(@category.restaurants)) %>
            </div>
          </div>
        </div>
      </div><!-- end col-md-12-->
    </div><!-- end row -->
  </div><!-- end container -->
<% else %>
  <%= render 'pages/navbar' %>

  <div class="jumbotron text-center">
    <h1><%= @category.name %></h1>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Assigned restaurants
          </div>

          <div class="card-body">
            <div id="all-restaurants">
              <%= render(Restaurants::ListingComponent.with_collection(@category.restaurants)) %>
            </div>
          </div>
        </div>
      </div><!-- end col-md-12-->
    </div><!-- end row -->
  </div><!-- end container -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <script src="https://kit.fontawesome.com/09425f7ba7.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">search<strong>ME</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to root_url, class: 'nav-link' do %>
            <i class="fas fa-home"></i> Home
          <% end %>
        </li>
      </ul>
      <div class="my-2 my-lg-0">
        <%= link_to "Get Started", new_user_registration_path, class: 'btn btn-outline-success my-2 my-sm-0' %>
      </div>
    </div>
  </div>
</nav>

app/views/pages/index.html.erb
<%= render 'navbar' %>

<div data-controller="search toast">
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= form_with(url: '/search', method: 'post') do |form| %>
            <%= form.text_field :query, 
              class: 'form-control form-control-lg d-inline-block col-12', 
              placeholder: 'Search for a restaurant...', autofocus: true,
              data: {'search-target': 'query', action: 'keyup->search#perform'}
            %>
          <% end %>
        </div>
      </div><!-- end row -->
      
      <div class="row">
        <div class="col-md-12 text-center">
          <%= render(Global::ButtonsCollectionComponent.with_collection(@categories)) %>
        </div>
      </div><!-- end row -->
    </div><!-- end container -->
  </div>

  <div class="container">
    <div class="col-md-12">
      <div id="results-counter"></div>
      <div id="restaurant_map"></div>
      <div id="results"></div>
    </div>
  </div>
</div>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-6">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group col-6">
      <%= form.label :address %><br />
      <%= form.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :about %><br />
    <%= form.text_area :about, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<%= turbo_frame_tag dom_id(restaurant) do %>
  <div class="card mb-2" id="<%= dom_id(restaurant) %>">
    <div class="card-body">
      <h5 class="card-title"><%= restaurant.name %></h5>
      <p class="card-text"><%= restaurant.about %></p>
      <p class="card-text">
        <%= restaurant.address %><br />
        <em><%= restaurant.latitude %>, <%= restaurant.longitude %></em>
      </p>

      <div class="mb-2">
        <% restaurant.categories.each do |category| %>
          <button class="btn btn-light btn-sm mr-1"><%= category.name %></button>
        <% end %>
      </div>

      <hr />
      
      <%= link_to "Assign Categories", restaurant, class: 'btn btn-primary', 'data-turbo-frame': :_top %>
      <%= link_to "Update Restaurant", edit_restaurant_path(restaurant), class: 'btn btn-warning' %>
      <%= link_to "Delete Restaurant", restaurant, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'admin_dashboards/navbar' %>

<div class="jumbotron text-center">
  <h1>Update Restaurant</h1>
  <%= link_to 'Back', restaurants_path, class: "btn btn-link" %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= turbo_frame_tag dom_id(@restaurant) do %>
        <%= render 'form', restaurant: @restaurant %>
      <% end %>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/restaurants/index.html.erb
<%= render 'admin_dashboards/navbar' %>

<div class="jumbotron text-center">
  <h1>Restaurants</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= turbo_stream_from "restaurants" %>

      <%= turbo_frame_tag "restaurant_form" do %>
        <%= render "restaurants/form", restaurant: @restaurant %>
      <% end %>

      <hr />
      <div class="mt-5">
        <%= turbo_frame_tag "restaurants" do %>
          <%= render @restaurants %>
        <% end %>
      </div>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/restaurants/new.html.erb
<%= render 'admin_dashboards/navbar' %>

<div class="jumbotron text-center">
  <h1>New Restaurant</h1>
  <%= link_to 'Back', restaurants_path, class: "btn btn-link" %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form', restaurant: @restaurant %>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/restaurants/show.html.erb
<% if admin_signed_in? %>
  <%= render 'admin_dashboards/navbar' %>
  
  <div class="jumbotron text-center">
    <h1><%= @restaurant.name %></h1>
    <%= link_to 'Update', edit_restaurant_path(@restaurant) %> | <%= link_to 'Back', restaurants_path, class: "btn btn-link" %>
  </div>

  <div class="container">
    <div id="already-exists-message"></div>

    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Assign restaurant to a category
          </div>
          <div class="card-body">
            <% @categories.each do |category| %>
              <button 
                class="btn btn-light" 
                data-reflex="click->AssignCategoryReflex#create"
                data-restaurant-id="<%= @restaurant.id %>"
                data-category-id="<%= category.id %>"
              ><i class="fas fa-plus"></i> <%= category.name %></button>
            <% end %>

            <hr />

            <%= render(Restaurants::Buttons::AssignedCategoriesComponent.with_collection(@assigned_categories, restaurant_id: @restaurant.id)) %>
          </div>
        </div>
      </div><!-- end col-md-12-->
    </div><!-- end row -->
    
    <div class="row mt-3">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Location
          </div>
          <div class="card-body">
            <p class="lead"><%= @restaurant.address %></p>
            <p><em><%= @restaurant.latitude %>, <%= @restaurant.longitude %></em></p>
          </div>
        </div>
      </div><!-- end col-md-12-->
    </div><!-- end row -->
    
    <div class="row mt-3">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            About
          </div>
          <div class="card-body">
            <p class="lead"><%= @restaurant.about %></p>
          </div>
        </div>
      </div><!-- end col-md-12-->
    </div><!-- end row -->
  </div><!-- end container -->

<% else %>
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @restaurant.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @restaurant.longitude %>
  </p>

  <p>
    <strong>About:</strong>
    <%= @restaurant.about %>
  </p>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>